services:
  - type: web
    name: chatroom
    env: java
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/chat-application-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: JAVA_HOME
        value: /opt/java/openjdk
      - key: SPRING_PROFILES_ACTIVE
        value: prod